risky: true

preset: laravel
version: 8

enabled:
  - strict
  - unalign_double_arrow

disabled:
  - short_array_syntax

finder:
  exclude:
    - "public"
    - "resources"
    - "tests"
  name:
    - "*.php"
